### ISSUE TITLE
New options and error

### ISSUE THREAD

**Issue by szogi1910** [kaganus/weapons#1]
Hi there is the possibility to set the given skin to the flag?
 If not, is there a possibility you would like this option added? 

Adding a search option name skins np. !ws truf
Adding a search option name np. !ws spectrum case

When we have a standard knife, after typing! Ws you can not select the knife

**Comment by kaganus** [comment]
Premium/VIP options will not be added, no flag restrictions.

Skin searching cannot be integrated into how the menus work atm, and there shouldn't be any need for that, since all new skins from new cases will always appear at the top of the skins list, even after updates.

Fixed the bug you mentioned in https://forums.alliedmods.net/showpost.php?p=2530806&postcount=10 on version v1.0.2
