### ISSUE TITLE
[Question] Gloves & VIP

### ISSUE THREAD

**Issue by wasyady** [kaganus/weapons#2]
I really like this plugin, best solution for ws!

I would like to ask if gloves are to be expected?
When to expect VIP feauture ?

**Comment by kaganus** [comment]
there will not be any VIP feature, people who want it, can add them themselves, source code is public anyway. (implementing VIP features would mean server owners earning money from selling VIP so their users can use my free plugin, while i get nothing for it. which feels kinda awkward doesn't it?)

gloves may be added, but probably as a separate plugin since what this plugin does is everything about weapons, but gloves is a totally another thing. doesn't make sense to merge them two into one plugin

**Comment by wasyady** [comment]
Thanks for answer!

I wait your gloves plugin!
