### ISSUE TITLE
Detection & Admin Flags

### ISSUE THREAD

**Issue by Shaneajm** [kaganus/weapons#21]
Hello, this isn't a bug report but more of a feature request/info. 

- Do you know the detection rate of this plugin? (a.k.a Valve Blacklisting) 

- Is there a command or option to make it for admins only?

If not I still love the features and menus/categories, great work!

**Comment by kaganus** [comment]
Detection rate is 100% since Valve auto detects memory changes through netprops, and there is no other way to apply skins to weapons. So any plugin that changes weapon skins will get automatically detected and GSLT banned every Monday/Wednesday/Friday at around 17:00 GMT

There is no flag support, as i mentioned on the Alliedmodders topic. You can use admin_overrides.cfg file to enable !ws !knife commands to only work for a specific flag, but you cannot assign a flag for each feature differently. For that you will have to buy private improvement from me or some other coder.

My reasoning behind this is, you shouldn't be able to gain anything (more VIP sales, more Steam Group members etc.) over my work that is distributed as free software. If you want the benefit, you have to give me some benefit in return, wouldn't you agree? :)
