### ISSUE TITLE
Error while changing a skin of a equipped weapon

### ISSUE THREAD

**Issue by alexcortes90** [kaganus/weapons#69]
http://prntscr.com/lxpddu
I get that error and server crashes completely

**Comment by kaganus** [comment]
use PTaH 1.0.9 .......

**Comment by alexcortes90** [comment]
using it

**Comment by kaganus** [comment]
then you dont have this problem, you cant have both

**Comment by alexcortes90** [comment]
how can i see if ptah is on and updated?

**Comment by kaganus** [comment]
type "sm exts list" on your server console, you should be seeing PTaH 1.0.9 without any errors

**Comment by alexcortes90** [comment]
http://prntscr.com/lxplr3

**Comment by kaganus** [comment]
then you have other plugins that use PTaH, remove them and it'll work. this was the problem when danger zone update hit. and was fixed in less than a day, there is nothing much to do except update everything, PTaH Sourcemod this plugin everything, and remove anything thats not updated since Danger Zone update.

**Comment by alexcortes90** [comment]
Solved man, thanks for all help 👍 :)
